env:
  node: true
  es6: true

extends:
  - "eslint:recommended"
  - "next/core-web-vitals"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "prettier"

plugins:
  - "unused-imports"

rules:
  import/order:
    - 2
    - alphabetize:
        order: "asc"

settings:
  import/resolver:
    typescript: ""
